// Package schema defines the core data types for MeshAnt.
//
// MeshAnt is a trace-first framework inspired by Actor-Network Theory.
// This package contains the [Trace] type: the fundamental unit of record.
//
// A Trace captures a moment where something made a difference in a network —
// a change, a redirection, a mediation, a transformation. It does not
// presuppose who or what the actors are. Actors are provisional effects
// of linked traces, not unquestioned first principles.
//
// This schema is provisional. It records a cut made at a particular time,
// from a particular observer position. That cut is itself part of the mesh.
// See docs/decisions/trace-schema-v1.md for the rationale behind what was
// included, excluded, and left open.
package schema

import (
	"errors"
	"regexp"
	"time"
)

// uuidPattern matches a lowercase hyphenated UUID string (any variant).
// Only lowercase hex is accepted; uppercase is rejected. The pattern does
// not constrain version or variant nibbles, allowing traces generated by
// systems that produce non-v4 UUIDs.
var uuidPattern = regexp.MustCompile(
	`^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`,
)

// TagValue is the type for descriptive trace tags.
// These constants are a starting vocabulary, not a closed enum.
// The Trace.Tags field is []string so that callers may supply
// descriptors not listed here without breaking the schema.
type TagValue string

const (
	TagDelay         TagValue = "delay"
	TagThreshold     TagValue = "threshold"
	TagBlockage      TagValue = "blockage"
	TagAmplification TagValue = "amplification"
	TagRedirection   TagValue = "redirection"
	TagTranslation   TagValue = "translation"
)

// Trace is a record of something that made a difference in a network.
//
// Source and Target are slices of strings. The schema does not yet decide
// what counts as an actor — that decision is deferred until enough traces
// have been followed to warrant it. A source or target could be a human,
// a rule, a threshold, a queue, a form, or anything else that redirects,
// amplifies, blocks, or transforms action. Using slices acknowledges that
// agency is often distributed across a heterogeneous assemblage; forcing a
// single name would perform a premature singularization of attribution.
//
// Fields with omitempty are optional. Their absence is meaningful:
// a Trace without a Mediation means no intermediary was observed —
// not that mediation is impossible.
//
// Use [Trace.Validate] to check that required fields are present.
type Trace struct {
	// ID uniquely identifies this trace record.
	// Must be a lowercase hyphenated UUID string.
	// Required.
	ID string `json:"id"`

	// Timestamp records when this trace was captured — not necessarily
	// when the underlying event "really" occurred. The distinction matters:
	// observation is always situated.
	// Required.
	Timestamp time.Time `json:"timestamp"`

	// WhatChanged is a short description of the difference that was made.
	// This is the primary content of the trace.
	// Required.
	WhatChanged string `json:"what_changed"`

	// Source names what produced this trace. A slice because the producer
	// of a difference is often a heterogeneous assemblage of elements
	// acting together. May be nil when attribution is genuinely unknown
	// or unattributable.
	Source []string `json:"source,omitempty"`

	// Target names what was affected. A slice for the same reason as
	// Source: effects are often distributed. May be nil when the effect
	// is diffuse or not yet observable.
	Target []string `json:"target,omitempty"`

	// Mediation names what transformed, redirected, or relayed the action
	// between source and target. Its absence means no intermediary was
	// observed — not that none could exist.
	Mediation string `json:"mediation,omitempty"`

	// Tags is a list of descriptors characterizing the kind of difference
	// this trace records. Uses the TagValue vocabulary as a starting point
	// but is not restricted to it — the field type is []string to keep
	// the vocabulary open and revisable.
	Tags []string `json:"tags,omitempty"`

	// Observer records who or what captured this trace, and from what
	// position. Different observers compose different worlds by rendering
	// different traces visible, relevant, and actionable.
	//
	// Required. A trace without a stated observer hides the cut that
	// made it — which contradicts Principle 8: the designer is inside
	// the mesh.
	Observer string `json:"observer"`
}

// Validate checks that the required fields of a Trace are present and
// well-formed. All violations are collected and returned together via
// [errors.Join], so callers receive the full set of problems in one pass.
//
// Required fields: ID (non-empty, valid lowercase UUID), Timestamp (non-zero),
// WhatChanged (non-empty), Observer (non-empty).
//
// Optional fields (Source, Target, Mediation, Tags) are never rejected
// by Validate — their absence is a valid and meaningful state.
func (t Trace) Validate() error {
	var errs []error
	if t.ID == "" {
		errs = append(errs, errors.New("trace: id is required"))
	} else if !uuidPattern.MatchString(t.ID) {
		errs = append(errs, errors.New("trace: id must be a valid UUID (lowercase hyphenated)"))
	}
	if t.Timestamp.IsZero() {
		errs = append(errs, errors.New("trace: timestamp is required and must not be zero"))
	}
	if t.WhatChanged == "" {
		errs = append(errs, errors.New("trace: what_changed is required"))
	}
	if t.Observer == "" {
		errs = append(errs, errors.New("trace: observer is required — record the position from which this trace was made"))
	}
	return errors.Join(errs...)
}
